name: Sync Help to GH-Pages

on:
  push:
    branches:
      - main
    paths:
      - "resources/help.html"

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Setup Git Config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Check for changes
        id: file_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'resources/help.html'; then
            echo "::set-output name=modified::true"
          fi

      - name: Copy file to gh-pages branch
        if: steps.file_check.outputs.modified == 'true'
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          cp resources/help.html docs/index.html
          git add docs/index.html
          git commit -m "Update docs/index.html from resources/help.html"
          git push origin gh-pages
