name: Sync Help to GH-Pages

on:
  push:
    branches:
      - main
    paths:
      - "resources/help.html"

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: "main"

      - name: Save help.html content
        run: |
          mkdir temp
          cp resources/help.html temp/help.html

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: "gh-pages"
          path: "gh-pages"

      - name: Merge main into gh-pages
        run: |
          cd gh-pages
          git merge origin/main --allow-unrelated-histories -m "Merge main to update help content"

      - name: Update docs/index.html
        run: |
          cp temp/help.html gh-pages/docs/index.html
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.html
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update docs/index.html from resources/help.html"
            git push origin gh-pages
          fi
